apiVersion: v1
kind: Service
metadata:
  labels:
    app: tracing-demo
  name: server-tracing
  namespace: default
spec:
  clusterIP: 172.20.49.90
  clusterIPs:
  - 172.20.49.90
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: tracing-demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}